-- Simple backup script
USE DATABASE TELCO_NETWORK_OPTIMIZATION_PROD;
USE SCHEMA RAW;

-- Create backup tables
CREATE OR REPLACE TABLE CELL_TOWER_BACKUP AS 
SELECT *, CURRENT_TIMESTAMP() AS BACKUP_TIMESTAMP 
FROM CELL_TOWER;

CREATE OR REPLACE TABLE SUPPORT_TICKETS_BACKUP AS 
SELECT *, CURRENT_TIMESTAMP() AS BACKUP_TIMESTAMP 
FROM SUPPORT_TICKETS;

-- Show backup counts
SELECT 'CELL_TOWER_BACKUP' as TABLE_NAME, COUNT(*) as RECORD_COUNT FROM CELL_TOWER_BACKUP
UNION ALL
SELECT 'SUPPORT_TICKETS_BACKUP' as TABLE_NAME, COUNT(*) as RECORD_COUNT FROM SUPPORT_TICKETS_BACKUP;
