-- Check detailed distribution of null/zero values by performance tier
SELECT 
    PERFORMANCE_TIER,
    COUNT(*) as total_rows,
    
    -- E-RAB establishment
    SUM(CASE WHEN PM_ERAB_ESTAB_ATT_INIT IS NULL OR PM_ERAB_ESTAB_ATT_INIT = 0 THEN 1 ELSE 0 END) as erab_att_null_zero,
    SUM(CASE WHEN PM_ERAB_ESTAB_SUCC_INIT IS NULL OR PM_ERAB_ESTAB_SUCC_INIT = 0 THEN 1 ELSE 0 END) as erab_succ_null_zero,
    
    -- S1 Signal
    SUM(CASE WHEN PM_S1_SIG_CONN_ESTAB_ATT IS NULL OR PM_S1_SIG_CONN_ESTAB_ATT = 0 THEN 1 ELSE 0 END) as s1_att_null_zero,
    SUM(CASE WHEN PM_S1_SIG_CONN_ESTAB_SUCC IS NULL OR PM_S1_SIG_CONN_ESTAB_SUCC = 0 THEN 1 ELSE 0 END) as s1_succ_null_zero,
    
    -- RSRP/RSRQ
    SUM(CASE WHEN PM_UE_MEAS_RSRP_DELTA_INTRA_FREQ1 IS NULL OR PM_UE_MEAS_RSRP_DELTA_INTRA_FREQ1 = 0 THEN 1 ELSE 0 END) as rsrp_delta_null_zero,
    SUM(CASE WHEN PM_UE_MEAS_RSRQ_DELTA_INTRA_FREQ1 IS NULL OR PM_UE_MEAS_RSRQ_DELTA_INTRA_FREQ1 = 0 THEN 1 ELSE 0 END) as rsrq_delta_null_zero,
    
    -- Volume
    SUM(CASE WHEN PM_PDCP_VOL_DL_DRB_LAST_TTI IS NULL OR PM_PDCP_VOL_DL_DRB_LAST_TTI = 0 THEN 1 ELSE 0 END) as vol_last_tti_null_zero
    
FROM TELCO_NETWORK_OPTIMIZATION_PROD.RAW.CELL_TOWER
GROUP BY PERFORMANCE_TIER
ORDER BY PERFORMANCE_TIER;

