select EVENT_DATE, count(*) from TELCO_NETWORK_OPTIMIZATION_PROD.RAW.CELL_TOWER group by EVENT_DATE order by EVENT_DATE desc;


select count(*) from TELCO_NETWORK_OPTIMIZATION_PROD.RAW.SUPPORT_TICKETS;

select CUSTOMER_NAME , avg(sentiment_score) from TELCO_NETWORK_OPTIMIZATION_PROD.RAW.SUPPORT_TICKETS group by CUSTOMER_NAME  order by 2 desc;

