-- Test the variety in our enhanced demo data

USE DATABASE TELCO_NETWORK_OPTIMIZATION_PROD;
USE SCHEMA RAW;

-- Test 1: Check RRC failure rate variety
SELECT 'RRC Failure Rate Test' as TEST,
    COUNT(*) as TOTAL_CELLS,
    MIN(ROUND(((PM_RRC_CONN_ESTAB_ATT - PM_RRC_CONN_ESTAB_SUCC) / PM_RRC_CONN_ESTAB_ATT * 100), 2)) as MIN_FAILURE_RATE,
    MAX(ROUND(((PM_RRC_CONN_ESTAB_ATT - PM_RRC_CONN_ESTAB_SUCC) / PM_RRC_CONN_ESTAB_ATT * 100), 2)) as MAX_FAILURE_RATE,
    COUNT(DISTINCT ROUND(((PM_RRC_CONN_ESTAB_ATT - PM_RRC_CONN_ESTAB_SUCC) / PM_RRC_CONN_ESTAB_ATT * 100), 1)) as DISTINCT_RATES
FROM CELL_TOWER 
WHERE PM_RRC_CONN_ESTAB_ATT > 0;

-- Test 2: Vendor distribution
SELECT 'Vendor Distribution' as TEST, VENDOR_NAME, COUNT(*) as COUNT
FROM CELL_TOWER 
GROUP BY VENDOR_NAME 
ORDER BY COUNT(*) DESC;

-- Test 3: PRB Utilization variety  
SELECT 'PRB Utilization Test' as TEST,
    MIN(PM_PRB_UTIL_DL) as MIN_DL_UTIL,
    MAX(PM_PRB_UTIL_DL) as MAX_DL_UTIL,
    COUNT(DISTINCT ROUND(PM_PRB_UTIL_DL, 0)) as DISTINCT_DL_VALUES
FROM CELL_TOWER;

-- Test 4: Top 5 worst RRC performers (perfect for demos!)
SELECT 'Top 5 Worst RRC Performers' as TEST,
    CELL_ID,
    BID_DESCRIPTION,
    VENDOR_NAME,
    ROUND(((PM_RRC_CONN_ESTAB_ATT - PM_RRC_CONN_ESTAB_SUCC) / PM_RRC_CONN_ESTAB_ATT * 100), 2) as FAILURE_RATE_PERCENT
FROM CELL_TOWER 
WHERE PM_RRC_CONN_ESTAB_ATT > 0
ORDER BY FAILURE_RATE_PERCENT DESC
LIMIT 5;

-- Test 5: Sentiment score variety
SELECT 'Sentiment Score Test' as TEST,
    MIN(SENTIMENT_SCORE) as MIN_SENTIMENT,
    MAX(SENTIMENT_SCORE) as MAX_SENTIMENT,
    COUNT(CASE WHEN SENTIMENT_SCORE < -0.5 THEN 1 END) as VERY_NEGATIVE_COUNT,
    COUNT(CASE WHEN SENTIMENT_SCORE > 0.5 THEN 1 END) as POSITIVE_COUNT
FROM SUPPORT_TICKETS;
