-- Verify sample data for the user's originally mentioned columns
SELECT 
    CELL_ID,
    PERFORMANCE_TIER,
    VENDOR_NAME,
    PM_ERAB_ESTAB_ATT_INIT,
    PM_ERAB_ESTAB_SUCC_INIT,
    PM_S1_SIG_CONN_ESTAB_ATT,
    PM_S1_SIG_CONN_ESTAB_SUCC,
    PM_UE_MEAS_RSRP_SERV_INTRA_FREQ1,
    PM_UE_MEAS_RSRP_DELTA_INTRA_FREQ1,
    PM_UE_MEAS_RSRQ_SERV_INTRA_FREQ1,
    PM_UE_MEAS_RSRQ_DELTA_INTRA_FREQ1,
    PM_UE_THP_TIME_DL,
    PM_PDCP_VOL_DL_DRB,
    PM_PDCP_VOL_DL_DRB_LAST_TTI
FROM TELCO_NETWORK_OPTIMIZATION_PROD.RAW.CELL_TOWER 
WHERE CELL_ID IS NOT NULL
ORDER BY RANDOM()
LIMIT 20;

