# Telco Network Optimization - Snowflake Streamlit Environment
# Simple package list format for Streamlit in Snowflake

# Core Streamlit and data processing
streamlit
pandas
numpy

# Geospatial and visualization
pydeck
plotly
matplotlib
h3-py
branca

# Statistical analysis  
scipy

# Snowflake integration (handled by Snowflake environment)
# snowflake-snowpark-python

# Additional utilities
altair