name: telco_network_optimization
channels:
  - snowflake
dependencies:
  - python=3.11.*
  - streamlit=
  - snowflake-snowpark-python=
  - pandas=
  - numpy=
  - pydeck=
  - matplotlib=
  - plotly=
  - altair=
  - scipy=
  - h3-py=
  - branca=