CREATE OR REPLACE CORTEX SEARCH SERVICE Network_Optimise_Cell_Tower_PM_PDCP_LAT_TIME_UL
ON PM_PDCP_LAT_TIME_UL
ATTRIBUTES CELL_ID, CALL_ID
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '364 day'
INITIALIZE = ON_CREATE
AS (
 SELECT PM_PDCP_LAT_TIME_UL
 FROM "TELCO_NETWORK_OPTIMIZATION_PROD"."RAW"."CELL_TOWER"
);