-- Create cortex search services with clean, descriptive names
-- Database: TELCO_NETWORK_OPTIMIZATION_PROD, Schema: RAW

-- CELL_TOWER: CAUSE_CODE_LONG_DESCRIPTION
CREATE OR REPLACE CORTEX SEARCH SERVICE TELCO_NETWORK_OPTIMIZATION_PROD.RAW.Network_Optimise_Cell_Tower_CAUSE_CODE_LONG_DESCRIPTION
ON CAUSE_CODE_LONG_DESCRIPTION
ATTRIBUTES CELL_ID, CALL_ID
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '364 day'
INITIALIZE = ON_SCHEDULE
AS (
 SELECT CAUSE_CODE_LONG_DESCRIPTION, CELL_ID, CALL_ID
 FROM "TELCO_NETWORK_OPTIMIZATION_PROD"."RAW"."CELL_TOWER"
);

-- CELL_TOWER: CAUSE_CODE_SHORT_DESCRIPTION
CREATE OR REPLACE CORTEX SEARCH SERVICE TELCO_NETWORK_OPTIMIZATION_PROD.RAW.Network_Optimise_Cell_Tower_CAUSE_CODE_SHORT_DESCRIPTION
ON CAUSE_CODE_SHORT_DESCRIPTION
ATTRIBUTES CELL_ID, CALL_ID
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '364 day'
INITIALIZE = ON_SCHEDULE
AS (
 SELECT CAUSE_CODE_SHORT_DESCRIPTION, CELL_ID, CALL_ID
 FROM "TELCO_NETWORK_OPTIMIZATION_PROD"."RAW"."CELL_TOWER"
);

-- CELL_TOWER: PM_PDCP_LAT_TIME_UL
CREATE OR REPLACE CORTEX SEARCH SERVICE TELCO_NETWORK_OPTIMIZATION_PROD.RAW.Network_Optimise_Cell_Tower_PM_PDCP_LAT_TIME_UL
ON PM_PDCP_LAT_TIME_UL
ATTRIBUTES CELL_ID, CALL_ID
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '364 day'
INITIALIZE = ON_SCHEDULE
AS (
 SELECT PM_PDCP_LAT_TIME_UL, CELL_ID, CALL_ID
 FROM "TELCO_NETWORK_OPTIMIZATION_PROD"."RAW"."CELL_TOWER"
);

-- SUPPORT_TICKETS: REQUEST
CREATE OR REPLACE CORTEX SEARCH SERVICE TELCO_NETWORK_OPTIMIZATION_PROD.RAW.Network_Optimise_Support_Tickets_REQUEST
ON REQUEST
ATTRIBUTES TICKET_ID
WAREHOUSE = MYOPSXSMALL
EMBEDDING_MODEL = 'snowflake-arctic-embed-l-v2.0'
TARGET_LAG = '364 day'
INITIALIZE = ON_SCHEDULE
AS (
 SELECT REQUEST, TICKET_ID
 FROM "TELCO_NETWORK_OPTIMIZATION_PROD"."RAW"."SUPPORT_TICKETS"
);

