-- Resume all cortex search services
-- Run this script manually when you want to resume the searches

ALTER CORTEX SEARCH SERVICE TELCO_NETWORK_OPTIMIZATION_PROD.RAW.Network_Optimise_Cell_Tower_CAUSE_CODE_LONG_DESCRIPTION RESUME;
ALTER CORTEX SEARCH SERVICE TELCO_NETWORK_OPTIMIZATION_PROD.RAW.Network_Optimise_Cell_Tower_CAUSE_CODE_SHORT_DESCRIPTION RESUME;
ALTER CORTEX SEARCH SERVICE TELCO_NETWORK_OPTIMIZATION_PROD.RAW.Network_Optimise_Cell_Tower_PM_PDCP_LAT_TIME_UL RESUME;
ALTER CORTEX SEARCH SERVICE TELCO_NETWORK_OPTIMIZATION_PROD.RAW.Network_Optimise_Support_Tickets_REQUEST RESUME;

