-- Suspend all cortex search services to save costs
-- Run this script manually when you want to suspend the searches

ALTER CORTEX SEARCH SERVICE TELCO_NETWORK_OPTIMIZATION_PROD.RAW.Network_Optimise_Cell_Tower_CAUSE_CODE_LONG_DESCRIPTION SUSPEND;
ALTER CORTEX SEARCH SERVICE TELCO_NETWORK_OPTIMIZATION_PROD.RAW.Network_Optimise_Cell_Tower_CAUSE_CODE_SHORT_DESCRIPTION SUSPEND;
ALTER CORTEX SEARCH SERVICE TELCO_NETWORK_OPTIMIZATION_PROD.RAW.Network_Optimise_Cell_Tower_PM_PDCP_LAT_TIME_UL SUSPEND;
ALTER CORTEX SEARCH SERVICE TELCO_NETWORK_OPTIMIZATION_PROD.RAW.Network_Optimise_Support_Tickets_REQUEST SUSPEND;

